import { Schedule, User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Elijah Oyin",
    initials: "EO",
    totalHours: "1168.0hrs",
    weeklyHours: "38.0hrs",
    status: "On Leave",
    leaveRange: "Jan 8 - Jan 15",
    indicators: ["m", "di", "w", "do", "vr"],
  },
  {
    id: "2",
    name: "Diane Lane",
    initials: "DL",
    totalHours: "1158.0hrs",
    weeklyHours: "38.0hrs",
    status: "On Leave",
    leaveRange: "Jan 12 - Jan 28",
    indicators: ["m", "di", "w", "do", "vr"],
  },
  {
    id: "3",
    name: "Haico de Gast",
    initials: "HG",
    totalHours: "1168.0hrs",
    weeklyHours: "38.0hrs",
    status: "On Leave",
    leaveRange: "Jan 2 - Jan 9",
    indicators: ["m", "di", "w", "do", "vr"],
  },
];

export const MOCK_SCHEDULES: Schedule[] = [
  {
    id: "s1",
    userId: "3",
    userName: "Haico de Gast",
    userInitials: "HG",
    title: "Surgery",
    startTime: "11:00",
    endTime: "13:00",
    department: "Behandelingkamer1",
    date: "2025-09-08",
    color: "orange",
  },
  {
    id: "s2",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "11:00",
    endTime: "12:00",
    department: "Behandelingkamer1",
    date: "2025-09-08",
    color: "green",
  },
  {
    id: "s9",
    userId: "1",
    userName: "Elijah Oyin",
    userInitials: "EO",
    title: "Diagnostic",
    startTime: "11:00",
    endTime: "12:30",
    department: "Behandelingkamer1",
    date: "2025-09-08",
    color: "amber",
  },
  {
    id: "s10",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "12:00",
    endTime: "13:00",
    department: "Behandelingkamer1",
    date: "2025-09-08",
    color: "orange",
  },
  {
    id: "s3",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "11:30",
    endTime: "13:30",
    department: "Bijzonderheden-Verlof-Cursus",
    date: "2025-09-08",
    color: "amber",
  },
  {
    id: "s4",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "16:00",
    endTime: "00:00",
    department: "Financien",
    date: "2025-09-08",
    color: "green",
  },
  {
    id: "s5",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "11:30",
    endTime: "13:30",
    department: "Financien",
    date: "2025-09-08",
    color: "amber",
  },
  {
    id: "s6",
    userId: "3",
    userName: "Haico de Gast",
    userInitials: "HG",
    title: "Pijnspecialist",
    startTime: "13:00",
    endTime: "15:00",
    department: "Management",
    date: "2025-09-08",
    color: "orange",
  },
  {
    id: "s7",
    userId: "1",
    userName: "Elijah Oyin",
    userInitials: "EO",
    title: "Surgery",
    startTime: "09:00",
    endTime: "11:00",
    department: "Behandelingkamer1",
    date: "2025-09-09",
    color: "orange",
  },
  {
    id: "s8",
    userId: "2",
    userName: "Diane Lane",
    userInitials: "DL",
    title: "Pijnspecialist",
    startTime: "14:00",
    endTime: "16:00",
    department: "Financien",
    date: "2025-09-09",
    color: "green",
  },
];
